### ISSUE TITLE
set() on a bot creates strange error

### ISSUE THREAD

**Issue by eamanj** [empiricaly/meteor-empirica-core#45]
When I set an attribute on all players, including a bot, the intro steps go through but the game never starts. After waiting a minute in the lobby with the message "Game Loading ...You game will be starting shortly, get ready!", the server fails with the following error:

```
W20190121-18:12:16.824(-5)? (STDERR) attempting to update player status from wrong conn
W20190121-18:13:05.046(-5)? (STDERR) Players.methods.ready RangeError: Maximum call stack size exceeded
W20190121-18:13:05.046(-5)? (STDERR)     at String.replace (<anonymous>)
W20190121-18:13:05.047(-5)? (STDERR)     at Function.makeKeyGeneric (/media/disk1/eaman/research/polarization/outsider/node_modules/mongo-object/dist/mongo-object.js:1011:18)
W20190121-18:13:05.047(-5)? (STDERR)     at parseObj (/media/disk1/eaman/research/polarization/outsider/node_modules/mongo-object/dist/mongo-object.js:104:48)
W20190121-18:13:05.047(-5)? (STDERR)     at /media/disk1/eaman/research/polarization/outsider/node_modules/mongo-object/dist/mongo-object.js:153:13
W20190121-18:13:05.047(-5)? (STDERR)     at arrayEach (/media/disk1/eaman/research/polarization/outsider/node_modules/lodash.foreach/index.js:35:9)
W20190121-18:13:05.047(-5)? (STDERR)     at forEach (/media/disk1/eaman/research/polarization/outsider/node_modules/lodash.foreach/index.js:290:10)
W20190121-18:13:05.048(-5)? (STDERR)     at parseObj (/media/disk1/eaman/research/polarization/outsider/node_modules/mongo-object/dist/mongo-object.js:151:32)
W20190121-18:13:05.048(-5)? (STDERR)     at /media/disk1/eaman/research/polarization/outsider/node_modules/mongo-object/dist/mongo-object.js:175:15
W20190121-18:13:05.048(-5)? (STDERR)     at Array.forEach (<anonymous>)
W20190121-18:13:05.048(-5)? (STDERR)     at parseObj (/media/disk1/eaman/research/polarization/outsider/node_modules/mongo-object/dist/mongo-object.js:169:28)
W20190121-18:13:05.048(-5)? (STDERR)     at /media/disk1/eaman/research/polarization/outsider/node_modules/mongo-object/dist/mongo-object.js:175:15
W20190121-18:13:05.048(-5)? (STDERR)     at Array.forEach (<anonymous>)
W20190121-18:13:05.048(-5)? (STDERR)     at parseObj (/media/disk1/eaman/research/polarization/outsider/node_modules/mongo-object/dist/mongo-object.js:169:28)
W20190121-18:13:05.049(-5)? (STDERR)     at /media/disk1/eaman/research/polarization/outsider/node_modules/mongo-object/dist/mongo-object.js:153:13
W20190121-18:13:05.049(-5)? (STDERR)     at arrayEach (/media/disk1/eaman/research/polarization/outsider/node_modules/lodash.foreach/index.js:35:9)
W20190121-18:13:05.049(-5)? (STDERR)     at forEach (/media/disk1/eaman/research/polarization/outsider/node_modules/lodash.foreach/index.js:290:10)
```

when I set the attribute only for the human player, the error does not occur. BTW, the lobby message should read: "Your game will be starting shortly"  not "You game will be starting shortly".

**Comment by amaatouq** [comment]
@eamanj is this resolved or still open?

**Comment by amaatouq** [comment]
Also, you shouldn't do `bot.set()` in the intro steps (they do not exist yet) .. it should start in the game initiation `gameInit` and then you loop over them and add the attributes.

**Comment by eamanj** [comment]
I was setting the bot to have a player object rather than the player id. After the change, it started working.
