### ISSUE TITLE
updating player data in intro rounds creates error

### ISSUE THREAD

**Issue by eamanj** [empiricaly/meteor-empirica-core#54]
I am updating player data (player.set(..)) in intro rounds before gameInit.
It succeeds in setting the attributes, but the server dumps the following error message. any idea why?

```
I20190325-12:03:37.487(4.5)? Exception while invoking method 'Players.methods.updateData' { MongoError: Updating the path 'data' would create a conflict at 'data'
I20190325-12:03:37.492(4.5)?     at Function.create (/Users/eaman/.meteor/packages/npm-mongo/.3.1.1.1mmptof.qcqo++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/error.js:43:12)
I20190325-12:03:37.493(4.5)?     at toError (/Users/eaman/.meteor/packages/npm-mongo/.3.1.1.1mmptof.qcqo++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/utils.js:149:22)
I20190325-12:03:37.493(4.5)?     at coll.s.topology.update (/Users/eaman/.meteor/packages/npm-mongo/.3.1.1.1mmptof.qcqo++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/operations/collection_ops.js:1370:39)
I20190325-12:03:37.494(4.5)?     at /Users/eaman/.meteor/packages/npm-mongo/.3.1.1.1mmptof.qcqo++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:532:18
I20190325-12:03:37.494(4.5)?     at _combinedTickCallback (internal/process/next_tick.js:131:7)
I20190325-12:03:37.494(4.5)?     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
I20190325-12:03:37.494(4.5)?   driver: true,
I20190325-12:03:37.494(4.5)?   name: 'MongoError',
I20190325-12:03:37.495(4.5)?   index: 0,
I20190325-12:03:37.495(4.5)?   code: 40,
I20190325-12:03:37.495(4.5)?   errmsg: 'Updating the path \'data\' would create a conflict at \'data\'',
I20190325-12:03:37.496(4.5)?   [Symbol(mongoErrorContextSymbol)]: {} }
```

**Comment by npaton** [comment]
I could not reproduce this issue. Here's a small code excerpt of the test I ran:

```js
export default class InstructionStepOne extends React.Component {
  componentDidMount() {
    const { player } = this.props;
    player.set("foo", "bar");
    player.set("data", 1);
  }

  // ...
```

This does not throw an exception.

Would you have some code I could look at?

**Comment by eamanj** [comment]
I noticed this only happens when the attribute I set it to is empty string. The attribute comes from a radio button, so if left unanswered, the default empty string would be used.

**Comment by npaton** [comment]
There was indeed an issue when trying to set a value to and empty string. It should be fixed with v0.10.0: `meteor update empirica:core`. Reopen if you still see the issue. ⛵️

**Comment by npaton** [comment]
@eamanj Is this resolved for you?

**Comment by eamanj** [comment]
yep. looks like it. thanks
