### ISSUE TITLE
`player.round.submit()` throws an exception

### ISSUE THREAD

**Issue by eamanj** [empiricaly/meteor-empirica-core#68]
I keep getting this error in production. any idea what causes this?
`qanmr
2019-11-15 18:22:53-05:00Exception in setTimeout callback: Error: not permitted
qanmr
2019-11-15 18:22:53-05:00 at MethodInvocation.run (packages/empirica:core/api/player-stages/methods.js:86:13)
qanmr
2019-11-15 18:22:53-05:00 at ValidatedMethod._execute (packages/mdg:validated-method/validated-method.js:94:12)
qanmr
2019-11-15 18:22:53-05:00 at MethodInvocation.PlayerStages.methods.submit (packages/mdg:validated-method/validated-method.js:57:23)
qanmr
2019-11-15 18:22:53-05:00 at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
qanmr
2019-11-15 18:22:53-05:00 at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1689:15)
qanmr
2019-11-15 18:22:53-05:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
qanmr
2019-11-15 18:22:53-05:00 at resolve (packages/ddp-server/livedata_server.js:1687:36)
qanmr
2019-11-15 18:22:53-05:00 at new Promise (<anonymous>)
qanmr
2019-11-15 18:22:53-05:00 at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
qanmr
2019-11-15 18:22:53-05:00 at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
qanmr
2019-11-15 18:22:53-05:00 at ValidatedMethod.call (packages/mdg:validated-method/validated-method.js:70:30)
qanmr
2019-11-15 18:22:53-05:00 at Object.cb [as submit] (packages/empirica:core/api/player-stages/augment.js:38:21)
qanmr
2019-11-15 18:22:53-05:00 at Object.onStageTick (server/bots.js:35:21)
qanmr
2019-11-15 18:22:53-05:00 at botPlayers.forEach.botPlayer (packages/empirica:core/api/games/server/cron.js:82:15)
qanmr
2019-11-15 18:22:53-05:00 at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1107:16)
qanmr
2019-11-15 18:22:53-05:00 at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:887:44)
qanmr
2019-11-15 18:22:53-05:00 => awaited here:
qanmr
2019-11-15 18:22:53-05:00 at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
qanmr
2019-11-15 18:22:53-05:00 at Server.apply (packages/ddp-server/livedata_server.js:1638:14)
qanmr
2019-11-15 18:22:53-05:00 at ValidatedMethod.call (packages/mdg:validated-method/validated-method.js:70:30)
qanmr
2019-11-15 18:22:53-05:00 at Object.cb [as submit] (packages/empirica:core/api/player-stages/augment.js:38:21)
qanmr
2019-11-15 18:22:53-05:00 at Object.onStageTick (server/bots.js:35:21)
qanmr
2019-11-15 18:22:53-05:00 at botPlayers.forEach.botPlayer (packages/empirica:core/api/games/server/cron.js:82:15)
qanmr
2019-11-15 18:22:53-05:00 at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1107:16)
qanmr
2019-11-15 18:22:53-05:00 at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:887:44)
qanmr
2019-11-15 18:22:53-05:00 at Games.find.forEach.game (packages/empirica:core/api/games/server/cron.js:50:20)
qanmr
2019-11-15 18:22:53-05:00 at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1107:16)
qanmr
2019-11-15 18:22:53-05:00 at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:887:44)
qanmr
2019-11-15 18:22:53-05:00 at Object.task (packages/empirica:core/api/games/server/cron.js:25:23)
qanmr
2019-11-15 18:22:53-05:00 at run (packages/empirica:core/startup/server/cron.js:53:14)
qanmr
2019-11-15 18:22:53-05:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
qanmr
2019-11-15 18:22:53-05:00 at packages/meteor.js:550:25
qanmr
2019-11-15 18:22:53-05:00 at runWithEnvironment (packages/meteor.js:1286:24)`

**Comment by npaton** [comment]
It is raised after an attempt to re-submit a stage. `player.stage.submit()` should only called once per stage. Once a stage has been submitted, `player.stage.submitted` will become true. This value can be used to disable or hide any submit button.

Note, this error does not change any data, or corrupt any server state, the data in the db should still be valid. It could potentially break client-side state if in a critical path (usually it isn't). This error is meant as an indicator for the experimenter that submit has happened 2 or more times for a single player, and there might a problem in the logic where players are given a chance to submit more than once.

The error is not explicit at the moment, I will make it produce a more clear message in the next release.

**Comment by amaatouq** [comment]
sometimes players just spam the submit button. So on the client-side, I have something  like this
```javascript
    if (player.stage.submitted) {
      return this.renderSubmitted();
    } else {
      return this.renderSubmitButton();
}

  renderSubmitted() {
    return (
      <div className="task-response">
        <div className="response-submitted">
          <h5>Waiting on other players...</h5>
          Please wait until all players are ready
        </div>
      </div>
    );
  }

  renderSubmitButton() {
    return (
        <form>
          <TimedButton
            stage={stage}
            player={player}
            activateAt={60}
            onClick={this.handleSubmit} />
        </form>
    );
}
```

**Comment by eamanj** [comment]
@npaton but how could a player resubmit in a stage if I disable the submit button once submitted? I basically have code that is very similar to what Abdullah shared, so I am not sure how players can resubmit. Note that this has only happened in production. For example, would latency in rendering cause this?

**Comment by npaton** [comment]
If this is a common issue you are seeing, that would indicate a specific problem in your experiment, and I would be glad to look into your issue with some code. But if it is a rare occurrence it is indeed something that could happen from time to time, and should not be cause for worry, unless you are seeing it break the players' experience.

I will explain a bit of the technical details for here for clarification, and if anyone else encounters this issue occasionally and looks it up in the issues here.

Empirica (and the underlying framework, Meteor) uses what is commonly referred to as "latency compensation", which means data is first changed locally so that the UI can update immediately, then the changes are sent to the server. So generally, latency should not be an issue in a case like this one.

But there are a couple of cases where a command might be executed multiple times.

First, the latency compensation mechanism might not be executed within the same frame render. In our example here, if the player double clicks the submit button, and the execution of the first click is delayed for whatever reason, the second click might be accepted before the UI can remove the button, and the second click would go through.

Second, after the data change has been applied locally in the latency compensation mechanism, a request is sent to the server to update the database. If this request fails because of a networking issue (momentary loss of connection, packet loss), the request will be sent again. From the client point of view the request failed the first time, so it's fair to retry, but from the server's point of view, maybe the first request did work, it was just never relayed back to the client.

In this particular case, the error thrown was really meant to help the experiment developer detect the case they were allowing submit to be sent multiple times. In effect, it does not change anything if the player does submit multiple times, so I think I will now only show a warning in the logs, if it happen in development, and stop throwing an error in production.

**Comment by alexhustler** [comment]
@npaton I'm seeing this same issue on production and I can't reproduce locally. It's happening once every 4 or 5 rounds.

I'm going to try storing `isSubmitted` in the local state of the component, instead of relying on `player.stage.submitted`, to avoid this latency issue.

```
state = {
  isSubmitted: false,
};

handleSubmit = event => {
  event.preventDefault();
  this.props.player.stage.submit();
  this.setState({
    isSubmitted: true,
  });
};

if (this.state.isSubmitted || player.stage.submitted) {
  return this.renderSubmitted();
}
```

**Comment by npaton** [comment]
@hubertusputu1 Make sure submitting twice does not throw, but if already submitted it logs it to the console, in development. In production it does nothing.
