### ISSUE TITLE
Upgrade bcrypt in create-empirica-app to avoid meteor error on Catalina

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/meteor-empirica-core#88]
`create-empirica-app` currently requires bcrypt@3.0.3. There don't seem to be any Catalina prebuilds for the dependency, and meteor seems to be having issues building from scratch: https://github.com/meteor/meteor/issues/10928. (Or I've made some other mistake, TBD)

## Steps to Reproduce
The command:
```
npx create-empirica-app test
```
Yielding:
```
File "/Users/jameshoughton/.meteor/packages/meteor-tool/.1.9.1.u3le4z.md04++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1527, in _GetXcodeEnv
    if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
TypeError: '>=' not supported between instances of 'tuple' and 'str'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/jameshoughton/.meteor/packages/meteor-tool/.1.9.1.u3le4z.md04++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/Users/jameshoughton/.meteor/packages/meteor-tool/.1.9.1.u3le4z.md04++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/jameshoughton/.meteor/packages/meteor-tool/.1.9.1.u3le4z.md04++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/jameshoughton/Desktop/test/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/jameshoughton/Desktop/test/node_modules/bcrypt/lib/binding" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72" "--python=/usr/bin/python3" "--nodedir=/Users/jameshoughton/.meteor/packages/meteor-tool/.1.9.1.u3le4z.md04++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle"
gyp ERR! cwd /Users/jameshoughton/Desktop/test/node_modules/bcrypt
gyp ERR! node -v v12.16.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/jameshoughton/.meteor/packages/meteor-tool/.1.9.1.u3le4z.md04++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node /Users/jameshoughton/.meteor/packages/meteor-tool/.1.9.1.u3le4z.md04++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/jameshoughton/Desktop/test/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/jameshoughton/Desktop/test/node_modules/bcrypt/lib/binding --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72 --python=/usr/bin/python3 --nodedir=/Users/jameshoughton/.meteor/packages/meteor-tool/.1.9.1.u3le4z.md04++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle' (1)
```

## Possible Solution
A workaround for empirica would be to upgrade the bundle to bcrypt@3.0.8, which has pre-built binaries for Catalina.

## Environment
- Meteor 1.9.0 or 1.9-rc.1
- Node v12.16.1
- npm 6.13.7
- npx 6.13.7
- OSX Catalina 10.15.3
- Xcode 11.3.1, Build version 11C504

**Comment by npaton** [comment]
@hubertusputu1 I don't know what's the problem with bcrypt, it has been a pain for years, always something new. If we could stop depending on it, great. Still think it's needed for admin authentication. I don't think we can really easily replace authentication there at the moment. Maybe a simple bcrypt version update will help, otherwise, if we'll need dig into the root cause if it not wanted to build.

**Comment by JamesPHoughton** [comment]
I'm still getting this error with `meteor update` in a new app. Is it possible npm is still on previous version?

**Comment by npaton** [comment]
Sorry, this was not released yet. We will do a release early next week. It should fix the Catalina issue.

If you need a fix before the release, I've found the instructions here https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md to be working.

**Comment by JamesPHoughton** [comment]
Doesn't look like the fix made it to the `create-empirica-app` template:

https://github.com/empiricaly/create-empirica-app/blob/86bd4f9fe8f385451aa7515d809d49cc7ddf58a0/templates/basic/package.json#L9

**Comment by npaton** [comment]
This should be fixed now. We moved to bcrypt 4, which should no longer have these build problems. We also updated Meteor and most dependencies. ⛵
